name: diabetes_predictor
description: "A minimal Flutter app for diabetes risk prediction using a FastAPI + XGBoost backend."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo_dp.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
